layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # facebook: your_username
  # dribbble: your_username
  # linkedin: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration
    image_url: https://camo.githubusercontent.com/c631a8cd2a842be7d1da89f3dcac4c42375f794d/687474703a2f2f6a656e6b696e732d782e696f2f696d672f70726f66696c652e706e67

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Testing
    web_url: https://github.com/topics/testing
    image_url: https://avatars1.githubusercontent.com/ml/671?s=140&v=4
